package idl;

/**
* NodeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from node.idl
* Monday, December 11, 2017 10:20:43 AM BRST
*/

abstract public class NodeHelper
{
  private static String  _id = "IDL:Node:1.0";

  public static void insert (org.omg.CORBA.Any a, Node that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Node extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (NodeHelper.id (), "Node");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Node read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NodeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Node value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Node narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Node)
      return (Node)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _NodeStub stub = new _NodeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Node unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Node)
      return (Node)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _NodeStub stub = new _NodeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
