
/**
* NodeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from node.idl
* Monday, December 11, 2017 9:32:58 AM BRST
*/

public final class NodeHolder implements org.omg.CORBA.portable.Streamable
{
  public Node value = null;

  public NodeHolder ()
  {
  }

  public NodeHolder (Node initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NodeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NodeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NodeHelper.type ();
  }

}
