package idl;

/**
* Node.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from node.idl
* Monday, December 11, 2017 10:20:43 AM BRST
*/

public interface Node extends NodeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Node
