package idl;

/**
* NodeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from node.idl
* Monday, December 11, 2017 10:20:43 AM BRST
*/

public interface NodeOperations 
{
  void ask (int asker, int timestamp);
  void release (int sender, int timestamp);
  void reply (int sender, int timestamp);
  void alive ();
} // interface NodeOperations
