
/**
* NodeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from node.idl
* Monday, December 11, 2017 9:32:58 AM BRST
*/

public interface NodeOperations 
{
  void ask (int asker, int timestamp);
  void release (int sender, int timestamp);
} // interface NodeOperations
